[req]
distinguished_name = req_distinguished_name
req_extensions = v3_req

[req_distinguished_name]
CN = kafka.example.com

[v3_req]
subjectAltName = @alt_names

[alt_names]
DNS.1 = kafka.example.com
DNS.2 = localhost
IP.1 = 127.0.0.1
