sinks:
  - kafka
format: json
kafkasink:
  bootstrapservers: "localhost:9092"
  topic: "ktranslate-ssl-config-test"
  securityprotocol: "SSL"
  sslcafile: "/home/mikek/ktranslate/testing/ssl-certs/ca-cert"
  sslcertfile: "/home/mikek/ktranslate/testing/ssl-certs/kafka-server-cert"
  sslkeyfile: "/home/mikek/ktranslate/testing/ssl-certs/kafka-server-key"
  sslinsecure: false
  compression: "gzip"
  requiredacks: 1
rollup:
  maxmemoryMB: 128
  maxkeys: 10000
  emergencycleanup: true
  topk: 20
server:
  loglevel: "debug"
  logtostdout: true
  servicename: "ktranslate-ssl-config-test"
